name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: "--target x86_64-unknown-linux-gnu"
          - platform: "ubuntu-22.04"
            args: "--target aarch64-unknown-linux-gnu"
          - platform: "windows-latest"
            args: "--target x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        run: |
          rustup update
          rustup target add ${{ matrix.args == '--target aarch64-apple-darwin' && 'aarch64-apple-darwin' || 
                              matrix.args == '--target x86_64-apple-darwin' && 'x86_64-apple-darwin' || 
                              matrix.args == '--target aarch64-unknown-linux-gnu' && 'aarch64-unknown-linux-gnu' || 
                              matrix.args == '--target x86_64-unknown-linux-gnu' && 'x86_64-unknown-linux-gnu' || 
                              matrix.args == '--target x86_64-pc-windows-msvc' && 'x86_64-pc-windows-msvc'}}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            gcc-aarch64-linux-gnu

      - name: Install frontend dependencies
        run: yarn install

      - name: Extract version from src-tauri/tauri.conf.json (Windows)
        id: version
        shell: pwsh
        run: |
          $VERSION = (jq -r .version src-tauri/tauri.conf.json)
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        with:
          tagName: "rusti-v${{ env.VERSION }}"
          releaseName: "rusti v${{ env.VERSION }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
